'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmtDate=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'-';
let db=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY),vehicles=[],users=[],reservations=[],records=[];
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3500)}
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem('fleetTheme',t);if($('themeText'))$('themeText').textContent=t==='dark'?'Tema claro':'Tema escuro'}
function modal(id,on=true){$(id).classList.toggle('hidden',!on)}
async function verify(){const {data:{session}}=await db.auth.getSession();if(!session)return showLogin();const {data,error}=await db.rpc('is_fleet_admin');if(error||!data){await db.auth.signOut();return showLogin('Conta sem permissão administrativa.')}showAdmin();load()}
function showLogin(m){$('loginView').classList.remove('hidden');$('adminView').classList.add('hidden');if(m)toast(m)}function showAdmin(){$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden')}
$('loginForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));const {error}=await db.auth.signInWithPassword(p);if(error)return toast(error.message);verify()};$('logout').onclick=async()=>{await db.auth.signOut();showLogin()};
async function load(){try{const [v,u,r,l]=await Promise.all([db.from('vehicles').select('*').order('model'),db.from('fleet_users').select('*').order('full_name'),db.from('reservations_admin').select('*').order('created_at',{ascending:false}),db.from('loan_records_view').select('*').order('withdrawal_date',{ascending:false})]);for(const x of [v,u,r,l])if(x.error)throw x.error;vehicles=v.data||[];users=u.data||[];reservations=r.data||[];records=l.data||[];render()}catch(e){toast(e.message)}}
function render(){$('kVehicles').textContent=vehicles.filter(v=>v.active).length;$('kPending').textContent=reservations.filter(r=>r.status==='pending').length;$('kApproved').textContent=reservations.filter(r=>r.status==='approved').length;$('kOpen').textContent=records.filter(r=>r.status==='open').length;$('fleetBody').innerHTML=vehicles.map(v=>`<tr><td>${esc(v.project||'-')}</td><td><b>${esc(v.model)}</b></td><td>${esc(v.plate)}</td><td>${esc(v.manual_status||'auto')}</td><td>${v.active?'Sim':'Não'}</td><td><button class="btn small" onclick="editVehicle('${v.id}')">Editar</button></td></tr>`).join('');$('usersBody').innerHTML=users.map(u=>`<tr><td><b>${esc(u.full_name)}</b></td><td>${esc(u.email||'-')}</td><td>${esc(u.employee_number||'-')}</td><td>${esc(u.department||'-')}</td><td>${esc(u.job_title||'-')}</td><td>${u.active?'Sim':'Não'}</td><td><button class="btn small" onclick="editUser('${u.id}')">Editar</button></td></tr>`).join('');$('requestsBody').innerHTML=reservations.map(r=>`<tr><td><b>${esc(r.requester_name)}</b><br><small>${esc(r.requester_email||'')}</small></td><td>${esc(r.model)} · ${esc(r.plate)}</td><td>${fmtDate(r.start_date)} a ${fmtDate(r.end_date)}</td><td><span class="badge ${r.status}">${esc(r.status)}</span></td><td class="actions">${r.status==='pending'?`<button class="btn small primary" onclick="decide('${r.id}','approved')">Aprovar</button><button class="btn small danger" onclick="decide('${r.id}','rejected')">Rejeitar</button>`:''}<button class="btn small danger" onclick="deleteReservation('${r.id}')">Excluir</button></td></tr>`).join('');$('recordsBody').innerHTML=records.map(r=>`<tr><td>${esc(r.requester_name)}</td><td>${esc(r.model)} · ${esc(r.plate)}</td><td>${fmtDate(r.withdrawal_date)}</td><td>${fmtDate(r.expected_return_date)}</td><td>${esc(r.status)}</td><td>${Number(r.inspection_count||0)*50}%</td></tr>`).join('')}
function fillForm(form,obj){form.reset();Object.entries(obj||{}).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v??''})}
window.editVehicle=id=>{const v=vehicles.find(x=>x.id===id);fillForm($('vehicleForm'),v);$('vehicleForm').active.value=String(v?.active??true);modal('vehicleModal')};window.editUser=id=>{const u=users.find(x=>x.id===id);fillForm($('userForm'),u);$('userForm').active.value=String(u?.active??true);modal('userModal')};
$('newVehicle').onclick=()=>{fillForm($('vehicleForm'),{});$('vehicleForm').active.value='true';$('vehicleForm').manual_status.value='auto';modal('vehicleModal')};$('newUser').onclick=()=>{fillForm($('userForm'),{});$('userForm').active.value='true';modal('userModal')};
$('vehicleForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget)),id=p.id;delete p.id;p.active=p.active==='true';Object.keys(p).forEach(k=>{if(p[k]==='')p[k]=null});const q=id?db.from('vehicles').update(p).eq('id',id):db.from('vehicles').insert(p);const {error}=await q;if(error)return toast(error.message);modal('vehicleModal',false);toast('Veículo salvo.');load()};
$('userForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget)),id=p.id;delete p.id;p.active=p.active==='true';Object.keys(p).forEach(k=>{if(p[k]==='')p[k]=null});const q=id?db.from('fleet_users').update(p).eq('id',id):db.from('fleet_users').insert(p);const {error}=await q;if(error)return toast(error.message);modal('userModal',false);toast('Usuário salvo.');load()};
window.decide=async(id,status)=>{const {error}=await db.rpc('set_reservation_status',{p_reservation_id:id,p_status:status});if(error)return toast(error.message);toast('Solicitação atualizada.');load()};window.deleteReservation=async id=>{if(!confirm('Excluir esta reserva e o empréstimo vinculado?'))return;const {error}=await db.rpc('admin_delete_reservation',{p_reservation_id:id});if(error)return toast(error.message);toast('Reserva excluída.');load()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-close]');if(b)modal(b.dataset.close,false)});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));['fleet','users','requests','records'].forEach(t=>$(t+'Tab').classList.toggle('hidden',t!==b.dataset.tab))});$('themeToggle').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');theme(localStorage.getItem('fleetTheme')||'dark');verify();
