let db,vehicles=[],reservations=[],selected=null;
const activeOn=(r,date=new Date())=>{const d=date.toISOString().slice(0,10);return r.status==='approved'&&r.start_date<=d&&r.end_date>=d};
const overlaps=(a1,a2,b1,b2)=>a1<=b2&&a2>=b1;
async function load(){try{db=getClient();const [{data:v,error:ve},{data:r,error:re}]=await Promise.all([db.from('vehicles').select('*').eq('active',true).order('model'),db.from('reservations_public').select('*').in('status',['pending','approved']).order('start_date')]);if(ve)throw ve;if(re)throw re;vehicles=v||[];reservations=r||[];$('source').classList.add('online');$('sourceText').textContent='Supabase conectado';fillProjects();render();}catch(e){$('sourceText').textContent='Erro de conexão';$('vehicleGrid').innerHTML=`<div class="empty">${esc(e.message)}</div>`;toast(e.message)}}
function fillProjects(){const ps=[...new Set(vehicles.map(v=>v.project).filter(Boolean))].sort();$('project').innerHTML='<option value="">Todos os projetos</option>'+ps.map(p=>`<option>${esc(p)}</option>`).join('')}
function vehicleState(v){const current=reservations.find(r=>r.vehicle_id===v.id&&activeOn(r));return{busy:!!current,current}}
function card(v){const s=vehicleState(v);const next=reservations.filter(r=>r.vehicle_id===v.id&&r.status==='approved'&&r.start_date>new Date().toISOString().slice(0,10)).sort((a,b)=>a.start_date.localeCompare(b.start_date))[0];return `<article class="vehicle-card ${s.busy?'unavailable':''}"><div class="vehicle-top"><div class="project">${esc(v.project||'-')}</div><div class="status ${s.busy?'off':''}">${s.busy?'INDISPONÍVEL':'DISPONÍVEL'}</div></div><h4>${esc(v.model)}</h4><div class="variant">${esc(v.version||'-')} · ${esc(v.color||'-')}</div><div class="facts"><div class="fact"><span>Placa</span><strong>${esc(v.plate)}</strong></div><div class="fact"><span>Usuário atual</span><strong>${esc(s.current?.requester_name||'-')}</strong></div><div class="fact"><span>Até</span><strong>${s.current?fmtDate(s.current.end_date):'-'}</strong></div><div class="fact"><span>Próxima reserva</span><strong>${next?fmtDate(next.start_date):'-'}</strong></div></div><div class="card-actions"><button class="btn" onclick="details('${v.id}')">Detalhes</button><button class="btn primary" onclick="openRequest('${v.id}')">${s.busy?'Request Reservation':'Request'}</button></div></article>`}
function render(){const q=$('search').value.toLowerCase(),p=$('project').value,a=$('availability').value;const rows=vehicles.filter(v=>{const busy=vehicleState(v).busy;return(!q||Object.values(v).join(' ').toLowerCase().includes(q))&&(!p||v.project===p)&&(!a||(a==='busy')===busy)});$('kTotal').textContent=vehicles.length;const busy=vehicles.filter(v=>vehicleState(v).busy).length;$('kAvailable').textContent=vehicles.length-busy;$('kBusy').textContent=busy;$('kPending').textContent=reservations.filter(r=>r.status==='pending').length;$('count').textContent=rows.length;$('vehicleGrid').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">Nenhum veículo encontrado.</div>';const upcoming=reservations.filter(r=>r.end_date>=new Date().toISOString().slice(0,10)).slice(0,12);$('reservationGrid').innerHTML=upcoming.length?upcoming.map(r=>`<article class="panel reservation ${r.status}"><span class="badge ${r.status}">${statusLabel[r.status]}</span><h4>${esc(r.model)} · ${esc(r.plate)}</h4><p><strong>${esc(r.requester_name)}</strong></p><p>${fmtDate(r.start_date)} a ${fmtDate(r.end_date)}</p><p>Projeto: ${esc(r.project||'-')}</p></article>`).join(''):'<div class="empty">Não há reservas futuras.</div>'}
function details(id){const v=vehicles.find(x=>x.id===id);alert(`${v.model} ${v.version||''}\nPlaca: ${v.plate}\nCor: ${v.color||'-'}\nAno/Modelo: ${v.year_model||'-'}\nRodízio: ${v.rotation_day||'-'}`)}
function openRequest(id){selected=vehicles.find(x=>x.id===id);const f=$('requestForm');f.reset();f.elements.vehicle_id.value=id;f.elements.project.value=selected.project||'';f.elements.start_date.min=new Date().toISOString().slice(0,10);f.elements.end_date.min=new Date().toISOString().slice(0,10);$('selectedVehicle').textContent=`${selected.model} · ${selected.plate}`;$('conflictWarning').classList.add('hidden');$('requestModal').classList.remove('hidden')}
function closeRequest(){$('requestModal').classList.add('hidden')}
function checkConflict(){const f=$('requestForm'),s=f.elements.start_date.value,e=f.elements.end_date.value,w=$('conflictWarning');if(!s||!e){w.classList.add('hidden');return}if(e<s){w.textContent='A data final não pode ser anterior à data inicial.';w.classList.remove('hidden');return}const hits=reservations.filter(r=>r.vehicle_id===selected.id&&r.status==='approved'&&overlaps(s,e,r.start_date,r.end_date));if(hits.length){w.innerHTML=`Conflito identificado com reserva aprovada de <strong>${fmtDate(hits[0].start_date)} a ${fmtDate(hits[0].end_date)}</strong>. A solicitação ainda pode ser enviada para análise.`;w.classList.remove('hidden')}else w.classList.add('hidden')}
$('requestForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.elements.start_date.value,en=f.elements.end_date.value;if(en<s)return toast('Revise o período informado.');const btn=$('submitRequest');btn.disabled=true;try{const payload=Object.fromEntries(new FormData(f));payload.vehicle_id=selected.id;payload.status='pending';const {error}=await db.from('reservations').insert(payload);if(error)throw error;toast('Solicitação enviada e registrada como pendente.');closeRequest();await load()}catch(err){toast('Não foi possível enviar: '+err.message)}finally{btn.disabled=false}};
['start_date','end_date'].forEach(n=>$('requestForm').elements[n].addEventListener('change',checkConflict));$('closeModal').onclick=$('cancelModal').onclick=closeRequest;$('requestModal').onclick=e=>{if(e.target===$('requestModal'))closeRequest()};$('search').oninput=render;$('project').onchange=$('availability').onchange=render;$('clear').onclick=()=>{$('search').value='';$('project').value='';$('availability').value='';render()};$('themeToggle').onclick=toggleTheme;load();
