"use strict";
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=v=>v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"-";
const nums=v=>String(v||"").replace(/\D/g,"");
const cpfMask=v=>nums(v).slice(0,11).replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2");
if(!window.APP_CONFIG||!window.supabase)throw new Error("Configuração do Supabase não carregada.");
const db=window.supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY);
let vehicles=[],users=[],reservations=[],records=[],editingUserId=null,editingVehicleId=null,busy=false;
function toast(m,e=false){const x=$("toast");x.textContent=m;x.style.borderColor=e?"var(--red)":"var(--green)";x.classList.add("show");setTimeout(()=>{x.classList.remove("show");x.style.removeProperty("border-color")},4500)}
function modal(id,on=true){$(id)?.classList.toggle("hidden",!on)}
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem("fleetTheme",t);$("themeText").textContent=t==="dark"?"Tema claro":"Tema escuro"}
async function verify(){const {data:{session}}=await db.auth.getSession();if(!session)return showLogin();const {data,error}=await db.rpc("is_fleet_admin");if(error||!data){await db.auth.signOut();return showLogin("Conta sem permissão administrativa.")}$("loginView").classList.add("hidden");$("adminView").classList.remove("hidden");load()}
function showLogin(m){$("loginView").classList.remove("hidden");$("adminView").classList.add("hidden");if(m)toast(m,true)}
async function load(){try{const [v,u,r,l]=await Promise.all([db.from("vehicles").select("*").order("model"),db.from("fleet_users").select("*").order("full_name"),db.from("reservations_admin").select("*").order("created_at",{ascending:false}),db.from("loan_records_view").select("*").order("withdrawal_date",{ascending:false})]);for(const q of[v,u,r,l])if(q.error)throw q.error;vehicles=v.data||[];users=u.data||[];reservations=r.data||[];records=l.data||[];render()}catch(e){console.error(e);toast(e.message,true)}}
function render(){$("kVehicles").textContent=vehicles.filter(v=>v.active).length;$("kPending").textContent=reservations.filter(r=>r.status==="pending").length;$("kApproved").textContent=reservations.filter(r=>r.status==="approved").length;$("kOpen").textContent=records.filter(r=>r.status==="open").length;$("fleetBody").innerHTML=vehicles.map(v=>`<tr><td>${esc(v.project||"-")}</td><td><b>${esc(v.model)}</b></td><td>${esc(v.plate)}</td><td>${esc(v.manual_status||"auto")}</td><td>${v.active?"Sim":"Não"}</td><td><button type="button" class="btn small" data-vehicle="${v.id}">Editar</button></td></tr>`).join("");$("usersBody").innerHTML=users.map(u=>`<tr><td><b>${esc(u.full_name)}</b></td><td>${esc(u.email||"-")}</td><td>${esc(u.employee_number||"-")}</td><td>${esc(u.department||"-")}</td><td>${esc(u.job_title||"-")}</td><td>${esc(u.cpf?cpfMask(u.cpf):"-")}</td><td>${esc(u.cnh||"-")}</td><td>${u.active?"Sim":"Não"}</td><td><button type="button" class="btn small" data-user="${u.id}">Editar</button></td></tr>`).join("");$("requestsBody").innerHTML=reservations.map(r=>`<tr><td><b>${esc(r.requester_name)}</b></td><td>${esc(r.model)} · ${esc(r.plate)}</td><td>${fmt(r.start_date)} a ${fmt(r.end_date)}</td><td>${esc(r.status)}</td><td class="actions">${r.status==="pending"?`<button type="button" class="btn small primary" data-decision="${r.id}" data-status="approved">Aprovar</button><button type="button" class="btn small danger" data-decision="${r.id}" data-status="rejected">Rejeitar</button>`:""}<button type="button" class="btn small danger" data-delete="${r.id}">Excluir</button></td></tr>`).join("");$("recordsBody").innerHTML=records.map(r=>`<tr><td>${esc(r.requester_name)}</td><td>${esc(r.model)} · ${esc(r.plate)}</td><td>${fmt(r.withdrawal_date)}</td><td>${fmt(r.expected_return_date)}</td><td>${esc(r.status)}</td><td>${Math.min(100,Number(r.inspection_count||0)*50)}%</td></tr>`).join("")}
function resetUser(){editingUserId=null;const f=$("userForm");f.reset();f.elements.id.value="";f.elements.active.value="true"}
function editUser(id){const u=users.find(x=>x.id===id);if(!u)return;editingUserId=id;const f=$("userForm");f.reset();for(const key of["full_name","email","employee_number","department","job_title","cpf","cnh"])f.elements[key].value=u[key]||"";f.elements.id.value=id;f.elements.active.value=String(u.active);$("userModalTitle").textContent="Editar usuário";modal("userModal")}
function editVehicle(id){const v=vehicles.find(x=>x.id===id);if(!v)return;editingVehicleId=id;const f=$("vehicleForm");f.reset();Object.entries(v).forEach(([k,val])=>{if(f.elements[k])f.elements[k].value=val??""});f.elements.id.value=id;f.elements.active.value=String(v.active);f.elements.manual_status.value=v.manual_status||"auto";$("vehicleModalTitle").textContent="Editar veículo";modal("vehicleModal")}
$("loginForm").onsubmit=async e=>{e.preventDefault();const {error}=await db.auth.signInWithPassword(Object.fromEntries(new FormData(e.currentTarget)));if(error)return toast(error.message,true);verify()};$("logout").onclick=async()=>{await db.auth.signOut();showLogin()};$("newUser").onclick=()=>{resetUser();$("userModalTitle").textContent="Novo usuário";modal("userModal")};$("newVehicle").onclick=()=>{editingVehicleId=null;const f=$("vehicleForm");f.reset();f.elements.id.value="";f.elements.active.value="true";f.elements.manual_status.value="auto";$("vehicleModalTitle").textContent="Novo veículo";modal("vehicleModal")};$("userForm").elements.cpf.oninput=e=>e.target.value=cpfMask(e.target.value);
$("userForm").onsubmit=async e=>{e.preventDefault();if(busy)return;const f=e.currentTarget,b=$("saveUserButton"),payload={p_id:editingUserId||null,p_full_name:f.elements.full_name.value.trim(),p_email:f.elements.email.value.trim()||null,p_employee_number:f.elements.employee_number.value.trim()||null,p_department:f.elements.department.value.trim()||null,p_job_title:f.elements.job_title.value.trim()||null,p_cpf:cpfMask(f.elements.cpf.value),p_cnh:f.elements.cnh.value.trim(),p_active:f.elements.active.value==="true"};if(nums(payload.p_cpf).length!==11)return toast("Informe um CPF com 11 dígitos.",true);if(!payload.p_cnh)return toast("Informe a CNH.",true);busy=true;b.disabled=true;b.textContent="Salvando...";try{const {data,error}=await db.rpc("admin_save_fleet_user",payload);if(error)throw error;if(!data)throw new Error("O banco não confirmou o salvamento.");toast(editingUserId?"Usuário atualizado com sucesso.":"Usuário cadastrado com sucesso.");resetUser();modal("userModal",false);await load()}catch(err){console.error(err);toast(err.message||"Falha ao salvar usuário.",true)}finally{busy=false;b.disabled=false;b.textContent="Salvar"}};
$("vehicleForm").onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));delete p.id;p.active=p.active==="true";Object.keys(p).forEach(k=>{if(p[k]==="")p[k]=null});const q=editingVehicleId?await db.from("vehicles").update(p).eq("id",editingVehicleId):await db.from("vehicles").insert(p);if(q.error)return toast(q.error.message,true);modal("vehicleModal",false);load()};
document.addEventListener("click",async e=>{const c=e.target.closest("[data-close]");if(c){if(c.dataset.close==="userModal")resetUser();return modal(c.dataset.close,false)}const u=e.target.closest("[data-user]");if(u)return editUser(u.dataset.user);const v=e.target.closest("[data-vehicle]");if(v)return editVehicle(v.dataset.vehicle);const d=e.target.closest("[data-decision]");if(d){const q=await db.rpc("set_reservation_status",{p_reservation_id:d.dataset.decision,p_status:d.dataset.status});if(q.error)return toast(q.error.message,true);toast("Solicitação atualizada.");return load()}const x=e.target.closest("[data-delete]");if(x&&confirm("Excluir esta reserva?")){const q=await db.rpc("admin_delete_reservation",{p_reservation_id:x.dataset.delete});if(q.error)return toast(q.error.message,true);load()}});document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));["fleet","users","requests","records"].forEach(t=>$(`${t}Tab`).classList.toggle("hidden",t!==b.dataset.tab))});$("themeToggle").onclick=()=>theme(document.documentElement.dataset.theme==="dark"?"light":"dark");theme(localStorage.getItem("fleetTheme")||"dark");verify();
