'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'-';
const localToday=()=>{const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`};
const statusLabel={pending:'Pendente',approved:'Aprovada',rejected:'Rejeitada',cancelled:'Cancelada',completed:'Concluída'};
let db,vehicles=[],reservations=[],users=[],inspections=[],selected=null,selectedLoan=null,damages=[],rotation=-24;
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3500)}
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem('fleetTheme',t);$('themeText').textContent=t==='dark'?'Tema claro':'Tema escuro'}
function showLoading(t,x){$('loadingTitle').textContent=t;$('loadingText').textContent=x;$('loading').classList.remove('hidden')}
function hideLoading(){$('loading').classList.add('hidden')}
function periodsOverlap(a,b,c,d){return a<=d&&b>=c}
function approvedFor(v){return reservations.filter(r=>r.vehicle_id===v.id&&r.status==='approved').sort((a,b)=>a.start_date.localeCompare(b.start_date))}
function vehicleState(v){const day=localToday();if(v.manual_status==='unavailable'&&(!v.manual_end_date||v.manual_end_date>=day))return{busy:true,current:v.current_driver||'Indisponível manualmente',start:v.manual_start_date,end:v.manual_end_date,next:null,loan:null,progress:0};if(v.manual_status==='available')return{busy:false,current:'-',start:null,end:null,next:null,loan:null,progress:0};const list=approvedFor(v),current=list.find(r=>r.start_date<=day&&r.end_date>=day),next=list.find(r=>r.start_date>day);if(!current)return{busy:false,current:'-',start:null,end:null,next,loan:null,progress:0};const loan=current.loan_record_id?{id:current.loan_record_id}:null;const count=inspections.filter(i=>i.loan_record_id===current.loan_record_id&&i.completed).length;return{busy:true,current:current.requester_name,start:current.start_date,end:current.end_date,next,loan,progress:Math.min(100,count*50),reservation:current}}
async function load(silent=false){try{if(!silent)showLoading('Sincronizando frota','Buscando veículos, reservas e vistorias...');db=db||supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY);const [v,r,u,i]=await Promise.all([db.from('vehicles').select('*').eq('active',true).order('model'),db.from('fleet_reservations_public').select('*').order('start_date'),db.rpc('list_fleet_users'),db.from('vehicle_inspections_public').select('*')]);for(const x of [v,r,u,i])if(x.error)throw x.error;vehicles=v.data||[];reservations=r.data||[];users=u.data||[];inspections=i.data||[];$('source').classList.add('online');$('sourceText').textContent='Supabase conectado';fillUsers();fillProjects();render();checkTrackedApprovals()}catch(e){$('sourceText').textContent='Erro de conexão';toast(e.message)}finally{if(!silent)hideLoading()}}
function fillUsers(){const current=$('fleetUser').value;$('fleetUser').innerHTML='<option value="">Selecione o usuário</option>'+users.map(u=>`<option value="${u.id}">${esc(u.full_name)}</option>`).join('');$('fleetUser').value=current}
function fillProjects(){const list=[...new Set(vehicles.map(v=>v.project).filter(Boolean))].sort(),cur=$('project').value;$('project').innerHTML='<option value="">Todos os projetos</option>'+list.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(list.includes(cur))$('project').value=cur}
function progressHtml(s){if(!s.busy||!s.loan)return'';const label=s.progress===0?'Vistoria de retirada pendente':s.progress===50?'Retirada concluída, devolução pendente':'Vistoria concluída';return `<button class="inspection-progress btn wide" data-inspect="1"><span class="progress-label"><b>Checklist / vistoria</b><span>${s.progress}%</span></span><span class="progress-track"><span class="progress-fill ${s.progress===100?'done':''}" style="--progress:${s.progress}%"></span></span><span class="progress-label"><span>${label}</span><span>${s.progress<100?'Preencher →':'Concluído ✓'}</span></span></button>`}
function card(v){const s=vehicleState(v);return `<article class="vehicle-card" tabindex="0" data-id="${v.id}"><div class="vehicle-top"><span class="project-tag">${esc(v.project||'-')}</span><span class="status ${s.busy?'off':''}"><i></i>${s.busy?'INDISPONÍVEL':'DISPONÍVEL'}</span></div><h3>${esc(v.model)}</h3><div class="variant">${esc(v.version||'-')} · ${esc(v.color||'-')}</div><div class="facts"><div><span>Placa</span><b>${esc(v.plate)}</b></div><div><span>Usuário atual</span><b>${esc(s.current)}</b></div><div><span>Período atual</span><b>${s.start?fmtDate(s.start)+' a '+fmtDate(s.end):'-'}</b></div><div><span>Próxima reserva</span><b>${s.next?fmtDate(s.next.start_date):'-'}</b></div></div>${progressHtml(s)}<button class="btn primary wide" data-request="1">${s.busy?'Solicitar outra data':'Solicitar veículo'}</button></article>`}
function render(){const q=$('search').value.toLowerCase(),p=$('project').value,a=$('availability').value;const rows=vehicles.filter(v=>{const s=vehicleState(v),text=Object.values(v).join(' ').toLowerCase();return(!q||text.includes(q))&&(!p||v.project===p)&&(!a||(a==='busy')===s.busy)});const busy=vehicles.filter(v=>vehicleState(v).busy).length;$('kTotal').textContent=vehicles.length;$('kAvailable').textContent=vehicles.length-busy;$('kBusy').textContent=busy;$('kPending').textContent=reservations.filter(r=>r.status==='pending').length;$('count').textContent=rows.length;$('vehicleGrid').innerHTML=rows.map(card).join('')||'<div class="empty">Nenhum veículo encontrado.</div>';const future=reservations.filter(r=>r.status==='pending'||(r.status==='approved'&&r.start_date>localToday())).sort((a,b)=>a.start_date.localeCompare(b.start_date));$('reservationGrid').innerHTML=future.map(r=>`<article class="reservation-card"><span class="badge ${r.status}">${statusLabel[r.status]}</span><h3>${esc(r.model)} · ${esc(r.plate)}</h3><p>${esc(r.requester_name)}</p><b>${fmtDate(r.start_date)} a ${fmtDate(r.end_date)}</b></article>`).join('')||'<div class="empty">Não há reservas futuras.</div>'}
function openDetails(id){selected=vehicles.find(v=>v.id===id);if(!selected)return;const s=vehicleState(selected);$('detailsTitle').textContent=selected.model;$('detailsSubtitle').textContent=`${selected.version||'-'} · ${selected.color||'-'}`;$('detailsGrid').innerHTML=[['Projeto',selected.project],['Status',s.busy?'Indisponível':'Disponível'],['Placa',selected.plate],['Ano / Modelo',selected.year_model],['Usuário atual',s.current],['Período atual',s.start?fmtDate(s.start)+' a '+fmtDate(s.end):'-'],['Próximo usuário',s.next?.requester_name||'-'],['Próxima reserva',s.next?fmtDate(s.next.start_date):'-']].map(([l,v])=>`<div><small>${l}</small><b>${esc(v||'-')}</b></div>`).join('');$('detailsModal').classList.remove('hidden')}
function openRequest(id){selected=vehicles.find(v=>v.id===id);if(!selected)return;const f=$('requestForm');f.reset();f.vehicle_id.value=id;f.start_date.min=f.end_date.min=localToday();$('selectedVehicle').textContent=`${selected.model} · ${selected.plate}`;$('conflictWarning').classList.add('hidden');$('requestModal').classList.remove('hidden')}
function checkConflict(){const f=$('requestForm'),s=f.start_date.value,e=f.end_date.value,w=$('conflictWarning');if(!s||!e)return w.classList.add('hidden');if(e<s){w.textContent='A data final não pode ser anterior à inicial.';return w.classList.remove('hidden')}const c=reservations.find(r=>r.vehicle_id===selected.id&&r.status==='approved'&&periodsOverlap(s,e,r.start_date,r.end_date));w.classList.toggle('hidden',!c);if(c)w.textContent=`Conflito com reserva aprovada de ${fmtDate(c.start_date)} a ${fmtDate(c.end_date)}. O banco impedirá a aprovação deste período.`}
$('requestForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));if(p.end_date<p.start_date)return toast('Revise o período.');showLoading('Enviando solicitação','Registrando os dados...');try{const {data,error}=await db.rpc('create_fleet_request',{p_vehicle_id:p.vehicle_id,p_fleet_user_id:p.fleet_user_id,p_start_date:p.start_date,p_end_date:p.end_date,p_purpose:p.purpose,p_notes:p.notes||null});if(error)throw error;const tokens=JSON.parse(localStorage.getItem('fleetRequestTokens')||'[]');tokens.push(data);localStorage.setItem('fleetRequestTokens',JSON.stringify([...new Set(tokens)]));$('requestModal').classList.add('hidden');toast('Solicitação enviada e salva para acompanhamento neste navegador.');await load(true)}catch(x){toast(x.message)}finally{hideLoading()}};
function openInspection(v){const s=vehicleState(v);if(!s.loan)return toast('Não há empréstimo ativo para este veículo.');if(s.progress===100)return toast('As duas vistorias deste empréstimo já foram concluídas.');selected=v;selectedLoan=s.loan;damages=[];renderDamages();const type=s.progress===0?'withdrawal':'return',f=$('inspectionForm');f.reset();f.loan_record_id.value=s.loan.id;f.inspection_type.value=type;f.inspection_date.value=localToday();f.inspection_time.value=new Date().toTimeString().slice(0,5);f.driver_name.value=s.current;$('inspectionTitle').textContent=type==='withdrawal'?'Checklist de Retirada':'Checklist de Devolução';$('driverLabel').firstChild.textContent=type==='withdrawal'?'Quem irá utilizar o veículo *':'Quem utilizou o veículo *';$('inspectionVehicle').textContent=`${v.model} · ${v.plate}`;$('inspectionModal').classList.remove('hidden')}
function renderDamages(){$('damageList').innerHTML=damages.map((d,i)=>`<div class="damage-item"><span><b>${esc(d.part)}</b><br><small>${esc(d.description)}</small></span><button type="button" class="btn small danger" data-remove-damage="${i}">Remover</button></div>`).join('')}
$('inspectionForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));try{const {error}=await db.rpc('submit_vehicle_inspection',{p_loan_record_id:p.loan_record_id,p_inspection_type:p.inspection_type,p_odometer_km:Number(p.odometer_km),p_inspection_date:p.inspection_date,p_inspection_time:p.inspection_time,p_inspector_name:p.inspector_name,p_driver_name:p.driver_name,p_vehicle_notes:p.vehicle_notes||null,p_damages:damages});if(error)throw error;$('inspectionModal').classList.add('hidden');toast('Vistoria concluída.');await load(true)}catch(x){toast(x.message)}};
async function checkTrackedApprovals(){const tokens=JSON.parse(localStorage.getItem('fleetRequestTokens')||'[]');if(!tokens.length)return;const seen=JSON.parse(localStorage.getItem('fleetApprovedSeen')||'[]');for(const token of tokens){const {data}=await db.rpc('track_fleet_request',{p_token:token});const r=Array.isArray(data)?data[0]:data;if(r?.status==='approved'&&!seen.includes(token)){seen.push(token);localStorage.setItem('fleetApprovedSeen',JSON.stringify(seen));$('contractMessage').textContent=`${r.model} · ${r.plate}, de ${fmtDate(r.start_date)} a ${fmtDate(r.end_date)}.`;$('downloadContract').onclick=()=>downloadContract(r);$('contractModal').classList.remove('hidden');break}}}
function downloadContract(r){const html=`<!doctype html><meta charset="utf-8"><style>body{font:16px Arial;max-width:800px;margin:50px auto;line-height:1.5}h1{text-align:center}</style><h1>Contrato de Comodato de Veículo</h1><p><b>Comodatário:</b> ${esc(r.requester_name)}</p><p><b>Dados funcionais:</b> ${esc(r.department||'-')} · ${esc(r.job_title||'-')} · ${esc(r.employee_number||'-')}</p><p><b>Veículo:</b> ${esc(r.model)} ${esc(r.version||'')} · Placa ${esc(r.plate)}</p><p><b>Período:</b> ${fmtDate(r.start_date)} a ${fmtDate(r.end_date)}</p><p><b>Finalidade:</b> ${esc(r.purpose)}</p><p>O usuário declara receber o veículo para a finalidade indicada e se compromete a devolvê-lo nas condições registradas no checklist.</p><br><br><p>____________________________________<br>${esc(r.requester_name)}</p>`;const blob=new Blob([html],{type:'application/msword'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Contrato_${r.plate}_${r.start_date}.doc`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}

document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){$(close.dataset.close).classList.add('hidden');return}const card=e.target.closest('.vehicle-card');if(card){const v=vehicles.find(x=>x.id===card.dataset.id);if(e.target.closest('[data-request]'))openRequest(v.id);else if(e.target.closest('[data-inspect]'))openInspection(v);else openDetails(v.id)}const remove=e.target.closest('[data-remove-damage]');if(remove){damages.splice(Number(remove.dataset.removeDamage),1);renderDamages()}const hot=e.target.closest('.hotspot');if(hot){$('damagePart').textContent=hot.dataset.part;$('damageEditor').dataset.part=hot.dataset.part;$('damageDescription').value='';$('damageEditor').classList.remove('hidden')}});
$('addDamage').onclick=()=>{const d=$('damageDescription').value.trim();if(!d)return toast('Detalhe a avaria.');damages.push({part:$('damageEditor').dataset.part,description:d});$('damageEditor').classList.add('hidden');renderDamages()};
let dragging=false,lastX=0;$('carStage').addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;$('carStage').setPointerCapture(e.pointerId)});$('carStage').addEventListener('pointermove',e=>{if(!dragging)return;rotation+=e.clientX-lastX;lastX=e.clientX;$('car3d').style.setProperty('--car-rotation',rotation+'deg')});$('carStage').addEventListener('pointerup',()=>dragging=false);
['start_date','end_date'].forEach(n=>$('requestForm')[n].onchange=checkConflict);$('themeToggle').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('search').oninput=render;$('project').onchange=$('availability').onchange=render;$('clear').onclick=()=>{$('search').value='';$('project').value='';$('availability').value='';render()};$('detailsRequest').onclick=()=>{$('detailsModal').classList.add('hidden');openRequest(selected.id)};theme(localStorage.getItem('fleetTheme')||'dark');load();setInterval(()=>load(true),60000);
