(() => {"use strict";
const C=window.APP_CONFIG,T=C.TABLES,S=C.STATUS;let db,state={vehicles:[],users:[],requests:[]};
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const toast=(m,t="")=>{const e=$("#toast");e.textContent=m;e.className=`toast show ${t}`;setTimeout(()=>e.className="toast",3200)};
const fmt=d=>d?new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(d+"T12:00:00Z")):"";
function open(id){const e=$("#"+id);e?.classList.remove("hidden");e?.setAttribute("aria-hidden","false")};function close(id){const e=$("#"+id);e?.classList.add("hidden");e?.setAttribute("aria-hidden","true")}
function active(r){const today=new Date().toISOString().slice(0,10);return r.status===S.approved&&r.start_date<=today&&r.end_date>=today}
function available(v){return v.manual_status!=="unavailable"&&!state.requests.some(r=>r.vehicle_id===v.id&&active(r))}
async function load(){
 const [v,u,r]=await Promise.all([db.from(T.vehicles).select("*").eq("active",true).order("model"),db.from(T.users).select("*").eq("active",true).order("full_name"),db.from(T.requests).select("*").order("created_at",{ascending:false})]);
 for(const x of [v,u,r])if(x.error)throw x.error;state={vehicles:v.data||[],users:u.data||[],requests:r.data||[]};render();
}
function render(){
 $("#kTotal").textContent=state.vehicles.length;$("#kAvailable").textContent=state.vehicles.filter(available).length;$("#kBusy").textContent=state.vehicles.filter(v=>!available(v)).length;$("#kPending").textContent=state.requests.filter(r=>r.status===S.pending).length;
 const p=$("#project"),old=p.value;p.innerHTML='<option value="">Todos os projetos</option>'+[...new Set(state.vehicles.map(v=>v.project).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join("");p.value=old;
 const q=$("#search").value.toLowerCase(),proj=p.value,av=$("#availability").value;const vs=state.vehicles.filter(v=>(!q||[v.project,v.model,v.plate].join(" ").toLowerCase().includes(q))&&(!proj||v.project===proj)&&(!av||(av==="available")===available(v)));
 $("#count").textContent=vs.length;$("#vehicleGrid").innerHTML=vs.map(v=>`<article class="vehicle-card" data-id="${v.id}"><span class="badge ${available(v)?'approved':''}">${available(v)?'Disponível':'Indisponível'}</span><h3>${esc(v.model)}</h3><p>${esc(v.project||'Sem projeto')} · ${esc(v.plate)}</p><button class="btn" data-details="${v.id}">Ver detalhes</button> ${available(v)?`<button class="btn primary" data-request="${v.id}">Solicitar</button>`:""}</article>`).join("")||'<div class="empty">Nenhum veículo encontrado.</div>';
 const future=state.requests.filter(r=>[S.pending,S.approved].includes(r.status));$("#reservationGrid").innerHTML=future.map(requestCard).join("")||'<div class="empty">Nenhuma reserva futura.</div>';
}
function requestCard(r){const v=state.vehicles.find(x=>x.id===r.vehicle_id)||{},u=state.users.find(x=>x.id===r.fleet_user_id)||{};const contract=makeContract(r,v,u);return `<article class="reservation-card" data-reservation-id="${r.id}"><span class="badge ${esc(r.status)}">${esc(r.status)}</span><h3>${esc(v.model||'Veículo')} · ${esc(v.plate||'')}</h3><p>${esc(u.full_name||'Usuário')}</p><strong>${fmt(r.start_date)} a ${fmt(r.end_date)}</strong>${r.status===S.pending?`<div class="contract-box"><strong>Aguardando assinatura do contrato</strong><p>Baixe o contrato, salve o PDF assinado no SharePoint e cole o link.</p><div class="contract-actions"><button class="btn primary" data-download="${r.id}">Baixar contrato</button></div><input data-contract-link value="${esc(r.signed_contract_url||'')}" placeholder="https://empresa.sharepoint.com/..."><div class="reservation-actions"><button class="btn primary" data-complete="${r.id}" ${r.signed_contract_url?'':'disabled'}>Concluir Solicitação</button><button class="btn danger" data-cancel="${r.id}">Cancelar reserva</button></div></div>`:""}</article>`}
function makeContract(r,v,u){return `<!doctype html><meta charset="utf-8"><title>Contrato de uso de veículo</title><style>body{font:16px Arial;max-width:800px;margin:50px auto;line-height:1.6}h1{text-align:center}.sig{margin-top:80px;display:flex;justify-content:space-between}.sig div{width:44%;border-top:1px solid;text-align:center}</style><h1>Termo de Responsabilidade de Uso de Veículo</h1><p>Solicitante: <b>${esc(u.full_name)}</b></p><p>Veículo: <b>${esc(v.model)} · ${esc(v.plate)}</b></p><p>Período: <b>${fmt(r.start_date)} a ${fmt(r.end_date)}</b></p><p>Finalidade: ${esc(r.purpose)}</p><p>O solicitante declara responsabilidade pela utilização e conservação do veículo durante o período informado, conforme normas internas aplicáveis.</p><div class="sig"><div>Solicitante</div><div>Responsável pela frota</div></div>`}
function startRequest(id){const v=state.vehicles.find(x=>x.id===id);if(!v)return;const f=$("#requestForm");f.reset();f.vehicle_id.value=id;$("#selectedVehicle").textContent=`${v.model} · ${v.plate}`;$("#fleetUser").innerHTML='<option value="">Selecione o usuário</option>'+state.users.map(u=>`<option value="${u.id}">${esc(u.full_name)}</option>`).join("");open("requestModal")}
async function submitRequest(e){e.preventDefault();const f=e.currentTarget,o=Object.fromEntries(new FormData(f));if(o.end_date<o.start_date)return toast("Data final inválida.","error");const conflict=state.requests.some(r=>r.vehicle_id===o.vehicle_id&&[S.pending,S.approved].includes(r.status)&&r.start_date<=o.end_date&&r.end_date>=o.start_date);if(conflict)return toast("Já existe reserva nesse período.","error");const b=$("#submitRequest");b.disabled=true;const {data,error}=await db.rpc("create_fleet_request",{p_vehicle_id:o.vehicle_id,p_fleet_user_id:o.fleet_user_id,p_start_date:o.start_date,p_end_date:o.end_date,p_purpose:o.purpose,p_notes:o.notes||null});b.disabled=false;if(error)return toast(error.message,"error");close("requestModal");toast("Solicitação enviada. Protocolo: "+(data||""),"success");await load()}
async function cancel(id){if(!confirm("Deseja cancelar esta reserva?"))return;const {error}=await db.from(T.requests).update({status:S.cancelled}).eq("id",id);if(error)return toast(error.message,"error");toast("Reserva cancelada.","success");load()}
async function complete(id,input){if(!/^https?:\/\//i.test(input.value.trim()))return toast("Informe um link válido.","error");const {error}=await db.from(T.requests).update({signed_contract_url:input.value.trim(),status:S.approved}).eq("id",id);if(error)return toast(error.message,"error");toast("Solicitação concluída.","success");load()}
function events(){document.addEventListener("click",e=>{const b=e.target.closest("button,[data-close]");if(!b)return;if(b.dataset.close)return close(b.dataset.close);if(b.dataset.request)return startRequest(b.dataset.request);if(b.dataset.details){const v=state.vehicles.find(x=>x.id===b.dataset.details);$("#detailsTitle").textContent=v.model;$("#detailsSubtitle").textContent=v.plate;$("#detailsGrid").innerHTML=Object.entries(v).filter(([k])=>!["id","created_at"].includes(k)).map(([k,x])=>`<div><small>${esc(k)}</small><strong>${esc(x)}</strong></div>`).join("");$("#detailsRequest").onclick=()=>{close("detailsModal");startRequest(v.id)};open("detailsModal")};if(b.dataset.cancel)cancel(b.dataset.cancel);if(b.dataset.download){const r=state.requests.find(x=>x.id===b.dataset.download),v=state.vehicles.find(x=>x.id===r.vehicle_id),u=state.users.find(x=>x.id===r.fleet_user_id);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([makeContract(r,v,u)],{type:"text/html"}));a.download=`contrato-${v.plate||r.id}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}if(b.dataset.complete){const card=b.closest(".reservation-card");complete(b.dataset.complete,card.querySelector("[data-contract-link]"))}});document.addEventListener("input",e=>{if(e.target.matches("[data-contract-link]")){const b=e.target.closest(".reservation-card").querySelector("[data-complete]");b.disabled=!/^https?:\/\//i.test(e.target.value.trim())}});["search","project","availability"].forEach(id=>$("#"+id)?.addEventListener(id==="search"?"input":"change",render));$("#clear")?.addEventListener("click",()=>{$("#search").value="";$("#project").value="";$("#availability").value="";render()});$("#requestForm")?.addEventListener("submit",submitRequest)}
async function init(){try{if(!window.supabase?.createClient)throw Error("SDK do Supabase não carregado.");db=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);window.fleetDb=db;events();await load();$("#source").classList.add("online");$("#sourceText").textContent="Conectado"}catch(e){console.error(e);$("#sourceText").textContent="Erro de conexão";toast(e.message,"error")}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();})();