"use strict";
(() => {
 const $=id=>document.getElementById(id);
 const esc=v=>String(v??"-").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),date=v=>v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"-",today=()=>new Intl.DateTimeFormat("pt-BR",{day:"numeric",month:"long",year:"numeric"}).format(new Date());
 function html(x){const v=[x.model,x.version].filter(Boolean).join(" ");return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Contrato</title><style>@page{size:A4;margin:18mm}body{font:11.5pt Arial;line-height:1.42;color:#111}h1{text-align:center;font-size:16pt}h2{font-size:11.5pt;margin-top:20px;text-transform:uppercase;border-bottom:1px solid #333}.box{border:1px solid #999;padding:10px;margin:10px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 18px}p{text-align:justify}.signature{margin-top:44px;border-top:1px solid #111;padding-top:5px}.no-print{text-align:right}@media print{.no-print{display:none}}</style></head><body><div class="no-print"><button onclick="print()">Imprimir / Salvar como PDF</button></div><h1>CONTRATO DE COMODATO DE VEÍCULO</h1><div class="box"><div class="grid"><div><b>Comodatário:</b> ${esc(x.requester_name)}</div><div><b>CPF:</b> ${esc(x.requester_cpf)}</div><div><b>CNH:</b> ${esc(x.requester_cnh)}</div><div><b>Matrícula:</b> ${esc(x.employee_number)}</div><div><b>Departamento:</b> ${esc(x.department)}</div><div><b>Cargo:</b> ${esc(x.job_title)}</div><div><b>E-mail:</b> ${esc(x.requester_email)}</div><div><b>Projeto:</b> ${esc(x.project)}</div></div></div><p>Pelo presente instrumento particular, de um lado, figurando como <b>COMODANTE:</b></p><p><b>HONDA AUTOMÓVEIS DO BRASIL LTDA.</b>, com sede na Estrada Municipal Valêncio Calegari, 777, Distrito de Nova Veneza, Sumaré/SP, e, de outro lado, o usuário identificado como <b>COMODATÁRIO</b>.</p><div class="box"><div class="grid"><div><b>Veículo:</b> ${esc(v)}</div><div><b>Placa:</b> ${esc(x.plate)}</div><div><b>Chassi:</b> ${esc(x.chassis)}</div><div><b>Renavam:</b> ${esc(x.renavam)}</div><div><b>Período:</b> ${date(x.start_date)} a ${date(x.end_date)}</div><div><b>Finalidade:</b> ${esc(x.purpose)}</div></div></div><h2>Conservação e condições de uso e restituição</h2><p>O COMODATÁRIO declara receber o veículo em condições de uso, responsabilizando-se por guarda, conservação, limpeza e restituição ao término deste contrato, ressalvado o desgaste normal.</p><p>Sinistros, falhas e necessidades de reparo deverão ser comunicados prontamente. É vedado reparar, alterar ou emprestar o veículo a terceiros sem autorização.</p><h2>Obrigações do Comodatário</h2><p>O COMODATÁRIO cumprirá as normas de trânsito e responderá pelas infrações e responsabilidades aplicáveis durante o período de uso.</p><h2>Confidencialidade e disposições finais</h2><p>O COMODATÁRIO manterá sigilo sobre os termos deste contrato e declara ciência das normas internas de uso da frota.</p><h2>Foro</h2><p>Fica eleito o Foro da Comarca de Sumaré (SP).</p><p>Sumaré, ${today()}.</p><div class="signature"><b>COMODATÁRIO</b><br>Assinatura:</div><div class="signature"><b>COMODANTE</b><br>Assinatura:</div></body></html>`}
 function word(x){const b=new Blob([html(x)],{type:"application/msword;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`Contrato_${String(x.plate||"veiculo").replace(/[^a-z0-9_-]/gi,"_")}_${x.start_date||"data"}.doc`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
 function pdf(x){const w=open("","_blank");if(!w)throw Error("Permita pop-ups para salvar em PDF.");w.document.write(html(x).replace("</body>",'<script>addEventListener("load",()=>setTimeout(()=>print(),250));<\\/script></body>'));w.document.close()}
 window.FleetContract={html,word,pdf};
 const hide=document.createElement("style");hide.textContent="#contractModal{display:none!important}";document.head.appendChild(hide);
 if(!window.APP_CONFIG||!window.supabase)return;const db=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY);let cache=[];
 async function load(){cache=[];let ts=[];try{ts=JSON.parse(localStorage.getItem("fleetRequestTokens")||"[]")}catch{}for(const token of ts){const {data}=await db.rpc("track_fleet_request",{p_token:token});const r=Array.isArray(data)?data[0]:data;if(r?.status==="approved")cache.push(r)}return cache}
 function match(card,r){const t=card.innerText;return t.includes(r.plate||"")&&t.includes(r.requester_name||"")}
 async function decorate(){await load();document.querySelectorAll("#reservationGrid .reservation-card").forEach(card=>{const r=cache.find(x=>match(card,x)),old=card.querySelector(".contract-download-button"),prior=card.querySelector(".contract-actions-final");if(!r){if(old){old.disabled=true;old.textContent="Contrato disponível ao solicitante"}prior?.remove();return}old?.remove();if(prior)return;const a=document.createElement("div");a.className="contract-actions-final";a.style.cssText="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px";a.innerHTML='<button class="btn" type="button">Baixar Word</button><button class="btn" type="button">Baixar PDF</button>';a.children[0].onclick=e=>{e.stopPropagation();word(r)};a.children[1].onclick=e=>{e.stopPropagation();pdf(r)};card.appendChild(a)})}
 const grid=$("reservationGrid");if(grid)new MutationObserver(()=>setTimeout(decorate,50)).observe(grid,{childList:true,subtree:true});setTimeout(decorate,100);
})();
